services:
  - type: web
    name: resume-grader-api
    env: python
    plan: starter
    buildCommand: pip install --only-binary=all -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: SARVAM_API_KEY
        sync: false
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1