services:
  - type: web
    name: resume-grader-api
    env: python
    runtime: python-3.11.9  # or python-3.10.14, python-3.9.19
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8000
    envVars:
      - key: SARVAM_API_KEY
        sync: false
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1